go2rtc:
  streams:
    webcam:
      - ffmpeg:device?video=0&video_size=640x360&input_format=mjpeg&framerate=5
    test_cam:
      - rtsp://mediamtx:8554/test_cam
    entrance_cam:
      - rtsp://mediamtx:8554/entrance_cam
    cam_1:
      - rtsp://admin:admin@193.56.148.190:554/live/ch00_0
    cam_2:
      - rtsp://admin:admin@213.129.131.54:554/live/ch00_0
    cam_3:
      - rtsp://admin:admin@46.167.248.2:554/live/ch00_0
    cam_4:
      - rtsp://admin:admin@85.187.195.198:554/live/ch00_0

# Tests:
detectors:
  cpu1:
    type: cpu

# Production:
#detectors:
#  coral:
#    type: edgetpu
#    device: usb

# MQTT
mqtt:
  enabled: true
  host: 192.168.1.67
  port: 1883
  user: frigate
  password: '1234'
  topic_prefix: frigate

# Face Recognition
face_recognition:
  enabled: true
  model_size: large

# License Plate Recognition
lpr:
  enabled: true
  detection_threshold: 0.7
  recognition_threshold: 0.9
  min_area: 1000
  min_plate_length: 4
  match_distance: 1
  known_plates:
    Leonardo:
      - SAZ1G92
      - GAZ1G92

# Objects tracked
objects:
  track:
    - person
    - car
    - motorcycle
    - cat
    - dog

# Cameras
cameras:
  webcam:
    ffmpeg:
      inputs:
        - path: rtsp://host.docker.internal:8554/webcam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio

    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5

    audio:
      enabled: true
      min_volume: 200
      listen:
        - fire_alarm
        - scream
        - yell

  test_cam:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://host.docker.internal:8554/test_cam
          roles:
            - detect
            - record
            - audio

    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5

    audio:
      enabled: true
      min_volume: 200
      listen:
        - fire_alarm
        - scream
        - yell

  entrance_cam:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://host.docker.internal:8554/entrance_cam
          roles:
            - detect
            - record

    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5

  cam_1:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://host.docker.internal:8554/cam_1
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5

  cam_2:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://host.docker.internal:8554/cam_2
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5

  cam_3:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://host.docker.internal:8554/cam_3
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5

  cam_4:
    ffmpeg:
      input_args: -rtsp_transport tcp
      inputs:
        - path: rtsp://host.docker.internal:8554/cam_4
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 5

# Classifications with Training photos
classification:
  custom:
    gestures:
      enabled: true
      name: gestures
      threshold: 0.7
      object_config:
        objects:
          - person
        classification_type: attribute
    identified_cars:
      enabled: true
      name: identified_cars
      threshold: 0.6
      object_config:
        objects:
          - car
        classification_type: sub_label
  bird:
    enabled: false

logger:
  default: info
  logs:
    frigate.data_processing.real_time.custom_classification: debug

version: 0.17-0